### ISSUE TITLE
[feat] 탭 계산기

### ISSUE THREAD

**Issue by wook95** [wanted-pre-onboading-10/exchange-rate-calculator#2]
# TASK CARD

Task Description : 탭이 5가지 있는 드롭다운 환율 계산기

Date : 22-01-25

## to-do

- [ ] 숫자 소수점 파싱
- [ ] 드롭다운에 따라 달라지는 탭
- [ ] api시 실시간 연동
