### ISSUE TITLE
[feat] 심플 계산기

### ISSUE THREAD

**Issue by hyundonmoon** [wanted-pre-onboading-10/exchange-rate-calculator#3]
# TASK CARD

Task Description : 송금액을 USD에서 KRW, JPY, PHP로 변환해주는 환율 계산기

Date : 22-01-25

## to-do
- [x] select box 선택 시 환율 즉시 반영
- [x] submit 후 수취금액을 계산 및 표시
- [x] 예외 상황 시 (0미만, 10000초과) 에러 문구 표시
